name: Deploy to GitHub Pages

# mainブランチへのpush、または手動トリガで実行
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npm run generate

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./.output/public  # Nuxt4の静的ファイル出力先

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
